/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products/route'
import { Route as ContactRouteImport } from './routes/contact/route'
import { Route as AboutRouteImport } from './routes/about/route'
import { Route as IndexRouteImport } from './routes/index/route'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as ProductsLaserMarkingMachinesRouteImport } from './routes/products/laser-marking-machines/route'
import { Route as ProductsLaserCuttingMachinesRouteImport } from './routes/products/laser-cutting-machines/route'
import { Route as ProductsLaserCleaningMachinesRouteImport } from './routes/products/laser-cleaning-machines/route'
import { Route as ProductsDotMarkingMachinesRouteImport } from './routes/products/dot-marking-machines/route'
import { Route as ProductsLaserMarkingMachinesIndexImport } from './routes/products/laser-marking-machines/index'
import { Route as ProductsLaserCuttingMachinesIndexImport } from './routes/products/laser-cutting-machines/index'
import { Route as ProductsLaserCleaningMachinesIndexImport } from './routes/products/laser-cleaning-machines/index'
import { Route as ProductsDotMarkingMachinesIndexImport } from './routes/products/dot-marking-machines/index'
import { Route as ProductsLaserMarkingMachinesUvLaserMarkerHuvSwMachineCrsLaserSourceImport } from './routes/products/laser-marking-machines/uv-laser-marker/huv-sw-machine-crs-laser-source'
import { Route as ProductsLaserMarkingMachinesUvLaserMarkerHuvMwPortableUvLaserMarkingMachineImport } from './routes/products/laser-marking-machines/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine'
import { Route as ProductsLaserMarkingMachinesUvLaserMarkerHuvIntegratedFiberLaserMarkingMachineImport } from './routes/products/laser-marking-machines/uv-laser-marker/huv-integrated-fiber-laser-marking-machine'
import { Route as ProductsLaserMarkingMachinesUvLaserMarkerHuvFwUvFlyingLaserMarkingMachineJptLaserSourceImport } from './routes/products/laser-marking-machines/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source'
import { Route as ProductsLaserMarkingMachinesPortableLaserMarkerHfiHModelHanheldLaserMarkingMachineImport } from './routes/products/laser-marking-machines/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine'
import { Route as ProductsLaserMarkingMachinesFiberLaserMarkerHfiSPulseFiberLaserMarkingMachineJptLaserSourceImport } from './routes/products/laser-marking-machines/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source'
import { Route as ProductsLaserMarkingMachinesFiberLaserMarkerHfiMnPortableMiniFiberLaserMarkingMachineImport } from './routes/products/laser-marking-machines/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine'
import { Route as ProductsLaserMarkingMachinesFiberLaserMarkerHfiMFiberLaserMarkerImport } from './routes/products/laser-marking-machines/fiber-laser-marker/hfi-m-fiber-laser-marker'
import { Route as ProductsLaserMarkingMachinesFiberLaserMarkerHfiFFiberFlyingLaserMarkingMachineJptLaserSourceImport } from './routes/products/laser-marking-machines/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source'
import { Route as ProductsLaserMarkingMachinesCo2LaserMarkerHcoScCo2LaserMarkingMachineCoherentLaserSourceImport } from './routes/products/laser-marking-machines/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source'
import { Route as ProductsLaserMarkingMachinesCo2LaserMarkerHcoFcCo2FlyingLaserMarkingMachineCoherentLaserSourceImport } from './routes/products/laser-marking-machines/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source'
import { Route as ProductsLaserCuttingMachinesLaserMetalCuttingMachineHcnC80CncLaserCuttingMachineImport } from './routes/products/laser-cutting-machines/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine'
import { Route as ProductsLaserCleaningMachinesHclLaserCleaningMachineHclLaserCleaningMachineImport } from './routes/products/laser-cleaning-machines/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine'
import { Route as ProductsDotMarkingMachinesHdoMarkingMachineHdoImport } from './routes/products/dot-marking-machines/hdo-marking-machine/hdo'

// Create/Update Routes

const ProductsRouteRoute = ProductsRouteImport.update({
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const ContactRouteRoute = ContactRouteImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRouteRoute = AboutRouteImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)

const ProductsLaserMarkingMachinesRouteRoute =
  ProductsLaserMarkingMachinesRouteImport.update({
    path: '/laser-marking-machines',
    getParentRoute: () => ProductsRouteRoute,
  } as any)

const ProductsLaserCuttingMachinesRouteRoute =
  ProductsLaserCuttingMachinesRouteImport.update({
    path: '/laser-cutting-machines',
    getParentRoute: () => ProductsRouteRoute,
  } as any)

const ProductsLaserCleaningMachinesRouteRoute =
  ProductsLaserCleaningMachinesRouteImport.update({
    path: '/laser-cleaning-machines',
    getParentRoute: () => ProductsRouteRoute,
  } as any)

const ProductsDotMarkingMachinesRouteRoute =
  ProductsDotMarkingMachinesRouteImport.update({
    path: '/dot-marking-machines',
    getParentRoute: () => ProductsRouteRoute,
  } as any)

const ProductsLaserMarkingMachinesIndexRoute =
  ProductsLaserMarkingMachinesIndexImport.update({
    path: '/',
    getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
  } as any)

const ProductsLaserCuttingMachinesIndexRoute =
  ProductsLaserCuttingMachinesIndexImport.update({
    path: '/',
    getParentRoute: () => ProductsLaserCuttingMachinesRouteRoute,
  } as any)

const ProductsLaserCleaningMachinesIndexRoute =
  ProductsLaserCleaningMachinesIndexImport.update({
    path: '/',
    getParentRoute: () => ProductsLaserCleaningMachinesRouteRoute,
  } as any)

const ProductsDotMarkingMachinesIndexRoute =
  ProductsDotMarkingMachinesIndexImport.update({
    path: '/',
    getParentRoute: () => ProductsDotMarkingMachinesRouteRoute,
  } as any)

const ProductsLaserMarkingMachinesUvLaserMarkerHuvSwMachineCrsLaserSourceRoute =
  ProductsLaserMarkingMachinesUvLaserMarkerHuvSwMachineCrsLaserSourceImport.update(
    {
      path: '/uv-laser-marker/huv-sw-machine-crs-laser-source',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesUvLaserMarkerHuvMwPortableUvLaserMarkingMachineRoute =
  ProductsLaserMarkingMachinesUvLaserMarkerHuvMwPortableUvLaserMarkingMachineImport.update(
    {
      path: '/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesUvLaserMarkerHuvIntegratedFiberLaserMarkingMachineRoute =
  ProductsLaserMarkingMachinesUvLaserMarkerHuvIntegratedFiberLaserMarkingMachineImport.update(
    {
      path: '/uv-laser-marker/huv-integrated-fiber-laser-marking-machine',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesUvLaserMarkerHuvFwUvFlyingLaserMarkingMachineJptLaserSourceRoute =
  ProductsLaserMarkingMachinesUvLaserMarkerHuvFwUvFlyingLaserMarkingMachineJptLaserSourceImport.update(
    {
      path: '/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesPortableLaserMarkerHfiHModelHanheldLaserMarkingMachineRoute =
  ProductsLaserMarkingMachinesPortableLaserMarkerHfiHModelHanheldLaserMarkingMachineImport.update(
    {
      path: '/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesFiberLaserMarkerHfiSPulseFiberLaserMarkingMachineJptLaserSourceRoute =
  ProductsLaserMarkingMachinesFiberLaserMarkerHfiSPulseFiberLaserMarkingMachineJptLaserSourceImport.update(
    {
      path: '/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesFiberLaserMarkerHfiMnPortableMiniFiberLaserMarkingMachineRoute =
  ProductsLaserMarkingMachinesFiberLaserMarkerHfiMnPortableMiniFiberLaserMarkingMachineImport.update(
    {
      path: '/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesFiberLaserMarkerHfiMFiberLaserMarkerRoute =
  ProductsLaserMarkingMachinesFiberLaserMarkerHfiMFiberLaserMarkerImport.update(
    {
      path: '/fiber-laser-marker/hfi-m-fiber-laser-marker',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesFiberLaserMarkerHfiFFiberFlyingLaserMarkingMachineJptLaserSourceRoute =
  ProductsLaserMarkingMachinesFiberLaserMarkerHfiFFiberFlyingLaserMarkingMachineJptLaserSourceImport.update(
    {
      path: '/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesCo2LaserMarkerHcoScCo2LaserMarkingMachineCoherentLaserSourceRoute =
  ProductsLaserMarkingMachinesCo2LaserMarkerHcoScCo2LaserMarkingMachineCoherentLaserSourceImport.update(
    {
      path: '/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserMarkingMachinesCo2LaserMarkerHcoFcCo2FlyingLaserMarkingMachineCoherentLaserSourceRoute =
  ProductsLaserMarkingMachinesCo2LaserMarkerHcoFcCo2FlyingLaserMarkingMachineCoherentLaserSourceImport.update(
    {
      path: '/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source',
      getParentRoute: () => ProductsLaserMarkingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserCuttingMachinesLaserMetalCuttingMachineHcnC80CncLaserCuttingMachineRoute =
  ProductsLaserCuttingMachinesLaserMetalCuttingMachineHcnC80CncLaserCuttingMachineImport.update(
    {
      path: '/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine',
      getParentRoute: () => ProductsLaserCuttingMachinesRouteRoute,
    } as any,
  )

const ProductsLaserCleaningMachinesHclLaserCleaningMachineHclLaserCleaningMachineRoute =
  ProductsLaserCleaningMachinesHclLaserCleaningMachineHclLaserCleaningMachineImport.update(
    {
      path: '/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine',
      getParentRoute: () => ProductsLaserCleaningMachinesRouteRoute,
    } as any,
  )

const ProductsDotMarkingMachinesHdoMarkingMachineHdoRoute =
  ProductsDotMarkingMachinesHdoMarkingMachineHdoImport.update({
    path: '/hdo-marking-machine/hdo',
    getParentRoute: () => ProductsDotMarkingMachinesRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRoute
    }
    '/products/dot-marking-machines': {
      id: '/products/dot-marking-machines'
      path: '/dot-marking-machines'
      fullPath: '/products/dot-marking-machines'
      preLoaderRoute: typeof ProductsDotMarkingMachinesRouteImport
      parentRoute: typeof ProductsRouteImport
    }
    '/products/laser-cleaning-machines': {
      id: '/products/laser-cleaning-machines'
      path: '/laser-cleaning-machines'
      fullPath: '/products/laser-cleaning-machines'
      preLoaderRoute: typeof ProductsLaserCleaningMachinesRouteImport
      parentRoute: typeof ProductsRouteImport
    }
    '/products/laser-cutting-machines': {
      id: '/products/laser-cutting-machines'
      path: '/laser-cutting-machines'
      fullPath: '/products/laser-cutting-machines'
      preLoaderRoute: typeof ProductsLaserCuttingMachinesRouteImport
      parentRoute: typeof ProductsRouteImport
    }
    '/products/laser-marking-machines': {
      id: '/products/laser-marking-machines'
      path: '/laser-marking-machines'
      fullPath: '/products/laser-marking-machines'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesRouteImport
      parentRoute: typeof ProductsRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof ProductsRouteImport
    }
    '/products/dot-marking-machines/': {
      id: '/products/dot-marking-machines/'
      path: '/'
      fullPath: '/products/dot-marking-machines/'
      preLoaderRoute: typeof ProductsDotMarkingMachinesIndexImport
      parentRoute: typeof ProductsDotMarkingMachinesRouteImport
    }
    '/products/laser-cleaning-machines/': {
      id: '/products/laser-cleaning-machines/'
      path: '/'
      fullPath: '/products/laser-cleaning-machines/'
      preLoaderRoute: typeof ProductsLaserCleaningMachinesIndexImport
      parentRoute: typeof ProductsLaserCleaningMachinesRouteImport
    }
    '/products/laser-cutting-machines/': {
      id: '/products/laser-cutting-machines/'
      path: '/'
      fullPath: '/products/laser-cutting-machines/'
      preLoaderRoute: typeof ProductsLaserCuttingMachinesIndexImport
      parentRoute: typeof ProductsLaserCuttingMachinesRouteImport
    }
    '/products/laser-marking-machines/': {
      id: '/products/laser-marking-machines/'
      path: '/'
      fullPath: '/products/laser-marking-machines/'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesIndexImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/dot-marking-machines/hdo-marking-machine/hdo': {
      id: '/products/dot-marking-machines/hdo-marking-machine/hdo'
      path: '/hdo-marking-machine/hdo'
      fullPath: '/products/dot-marking-machines/hdo-marking-machine/hdo'
      preLoaderRoute: typeof ProductsDotMarkingMachinesHdoMarkingMachineHdoImport
      parentRoute: typeof ProductsDotMarkingMachinesRouteImport
    }
    '/products/laser-cleaning-machines/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine': {
      id: '/products/laser-cleaning-machines/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine'
      path: '/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine'
      fullPath: '/products/laser-cleaning-machines/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine'
      preLoaderRoute: typeof ProductsLaserCleaningMachinesHclLaserCleaningMachineHclLaserCleaningMachineImport
      parentRoute: typeof ProductsLaserCleaningMachinesRouteImport
    }
    '/products/laser-cutting-machines/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine': {
      id: '/products/laser-cutting-machines/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine'
      path: '/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine'
      fullPath: '/products/laser-cutting-machines/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine'
      preLoaderRoute: typeof ProductsLaserCuttingMachinesLaserMetalCuttingMachineHcnC80CncLaserCuttingMachineImport
      parentRoute: typeof ProductsLaserCuttingMachinesRouteImport
    }
    '/products/laser-marking-machines/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source': {
      id: '/products/laser-marking-machines/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source'
      path: '/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source'
      fullPath: '/products/laser-marking-machines/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesCo2LaserMarkerHcoFcCo2FlyingLaserMarkingMachineCoherentLaserSourceImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source': {
      id: '/products/laser-marking-machines/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source'
      path: '/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source'
      fullPath: '/products/laser-marking-machines/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesCo2LaserMarkerHcoScCo2LaserMarkingMachineCoherentLaserSourceImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source': {
      id: '/products/laser-marking-machines/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source'
      path: '/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source'
      fullPath: '/products/laser-marking-machines/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesFiberLaserMarkerHfiFFiberFlyingLaserMarkingMachineJptLaserSourceImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/fiber-laser-marker/hfi-m-fiber-laser-marker': {
      id: '/products/laser-marking-machines/fiber-laser-marker/hfi-m-fiber-laser-marker'
      path: '/fiber-laser-marker/hfi-m-fiber-laser-marker'
      fullPath: '/products/laser-marking-machines/fiber-laser-marker/hfi-m-fiber-laser-marker'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesFiberLaserMarkerHfiMFiberLaserMarkerImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine': {
      id: '/products/laser-marking-machines/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine'
      path: '/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine'
      fullPath: '/products/laser-marking-machines/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesFiberLaserMarkerHfiMnPortableMiniFiberLaserMarkingMachineImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source': {
      id: '/products/laser-marking-machines/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source'
      path: '/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source'
      fullPath: '/products/laser-marking-machines/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesFiberLaserMarkerHfiSPulseFiberLaserMarkingMachineJptLaserSourceImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine': {
      id: '/products/laser-marking-machines/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine'
      path: '/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine'
      fullPath: '/products/laser-marking-machines/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesPortableLaserMarkerHfiHModelHanheldLaserMarkingMachineImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source': {
      id: '/products/laser-marking-machines/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source'
      path: '/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source'
      fullPath: '/products/laser-marking-machines/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesUvLaserMarkerHuvFwUvFlyingLaserMarkingMachineJptLaserSourceImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/uv-laser-marker/huv-integrated-fiber-laser-marking-machine': {
      id: '/products/laser-marking-machines/uv-laser-marker/huv-integrated-fiber-laser-marking-machine'
      path: '/uv-laser-marker/huv-integrated-fiber-laser-marking-machine'
      fullPath: '/products/laser-marking-machines/uv-laser-marker/huv-integrated-fiber-laser-marking-machine'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesUvLaserMarkerHuvIntegratedFiberLaserMarkingMachineImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine': {
      id: '/products/laser-marking-machines/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine'
      path: '/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine'
      fullPath: '/products/laser-marking-machines/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesUvLaserMarkerHuvMwPortableUvLaserMarkingMachineImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
    '/products/laser-marking-machines/uv-laser-marker/huv-sw-machine-crs-laser-source': {
      id: '/products/laser-marking-machines/uv-laser-marker/huv-sw-machine-crs-laser-source'
      path: '/uv-laser-marker/huv-sw-machine-crs-laser-source'
      fullPath: '/products/laser-marking-machines/uv-laser-marker/huv-sw-machine-crs-laser-source'
      preLoaderRoute: typeof ProductsLaserMarkingMachinesUvLaserMarkerHuvSwMachineCrsLaserSourceImport
      parentRoute: typeof ProductsLaserMarkingMachinesRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  AboutRouteRoute,
  ContactRouteRoute,
  ProductsRouteRoute: ProductsRouteRoute.addChildren({
    ProductsDotMarkingMachinesRouteRoute:
      ProductsDotMarkingMachinesRouteRoute.addChildren({
        ProductsDotMarkingMachinesIndexRoute,
        ProductsDotMarkingMachinesHdoMarkingMachineHdoRoute,
      }),
    ProductsLaserCleaningMachinesRouteRoute:
      ProductsLaserCleaningMachinesRouteRoute.addChildren({
        ProductsLaserCleaningMachinesIndexRoute,
        ProductsLaserCleaningMachinesHclLaserCleaningMachineHclLaserCleaningMachineRoute,
      }),
    ProductsLaserCuttingMachinesRouteRoute:
      ProductsLaserCuttingMachinesRouteRoute.addChildren({
        ProductsLaserCuttingMachinesIndexRoute,
        ProductsLaserCuttingMachinesLaserMetalCuttingMachineHcnC80CncLaserCuttingMachineRoute,
      }),
    ProductsLaserMarkingMachinesRouteRoute:
      ProductsLaserMarkingMachinesRouteRoute.addChildren({
        ProductsLaserMarkingMachinesIndexRoute,
        ProductsLaserMarkingMachinesCo2LaserMarkerHcoFcCo2FlyingLaserMarkingMachineCoherentLaserSourceRoute,
        ProductsLaserMarkingMachinesCo2LaserMarkerHcoScCo2LaserMarkingMachineCoherentLaserSourceRoute,
        ProductsLaserMarkingMachinesFiberLaserMarkerHfiFFiberFlyingLaserMarkingMachineJptLaserSourceRoute,
        ProductsLaserMarkingMachinesFiberLaserMarkerHfiMFiberLaserMarkerRoute,
        ProductsLaserMarkingMachinesFiberLaserMarkerHfiMnPortableMiniFiberLaserMarkingMachineRoute,
        ProductsLaserMarkingMachinesFiberLaserMarkerHfiSPulseFiberLaserMarkingMachineJptLaserSourceRoute,
        ProductsLaserMarkingMachinesPortableLaserMarkerHfiHModelHanheldLaserMarkingMachineRoute,
        ProductsLaserMarkingMachinesUvLaserMarkerHuvFwUvFlyingLaserMarkingMachineJptLaserSourceRoute,
        ProductsLaserMarkingMachinesUvLaserMarkerHuvIntegratedFiberLaserMarkingMachineRoute,
        ProductsLaserMarkingMachinesUvLaserMarkerHuvMwPortableUvLaserMarkingMachineRoute,
        ProductsLaserMarkingMachinesUvLaserMarkerHuvSwMachineCrsLaserSourceRoute,
      }),
    ProductsIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/products"
      ]
    },
    "/": {
      "filePath": "index/route.tsx"
    },
    "/about": {
      "filePath": "about/route.tsx"
    },
    "/contact": {
      "filePath": "contact/route.tsx"
    },
    "/products": {
      "filePath": "products/route.tsx",
      "children": [
        "/products/dot-marking-machines",
        "/products/laser-cleaning-machines",
        "/products/laser-cutting-machines",
        "/products/laser-marking-machines",
        "/products/"
      ]
    },
    "/products/dot-marking-machines": {
      "filePath": "products/dot-marking-machines/route.tsx",
      "parent": "/products",
      "children": [
        "/products/dot-marking-machines/",
        "/products/dot-marking-machines/hdo-marking-machine/hdo"
      ]
    },
    "/products/laser-cleaning-machines": {
      "filePath": "products/laser-cleaning-machines/route.tsx",
      "parent": "/products",
      "children": [
        "/products/laser-cleaning-machines/",
        "/products/laser-cleaning-machines/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine"
      ]
    },
    "/products/laser-cutting-machines": {
      "filePath": "products/laser-cutting-machines/route.tsx",
      "parent": "/products",
      "children": [
        "/products/laser-cutting-machines/",
        "/products/laser-cutting-machines/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine"
      ]
    },
    "/products/laser-marking-machines": {
      "filePath": "products/laser-marking-machines/route.tsx",
      "parent": "/products",
      "children": [
        "/products/laser-marking-machines/",
        "/products/laser-marking-machines/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source",
        "/products/laser-marking-machines/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source",
        "/products/laser-marking-machines/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source",
        "/products/laser-marking-machines/fiber-laser-marker/hfi-m-fiber-laser-marker",
        "/products/laser-marking-machines/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine",
        "/products/laser-marking-machines/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source",
        "/products/laser-marking-machines/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine",
        "/products/laser-marking-machines/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source",
        "/products/laser-marking-machines/uv-laser-marker/huv-integrated-fiber-laser-marking-machine",
        "/products/laser-marking-machines/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine",
        "/products/laser-marking-machines/uv-laser-marker/huv-sw-machine-crs-laser-source"
      ]
    },
    "/products/": {
      "filePath": "products/index.tsx",
      "parent": "/products"
    },
    "/products/dot-marking-machines/": {
      "filePath": "products/dot-marking-machines/index.tsx",
      "parent": "/products/dot-marking-machines"
    },
    "/products/laser-cleaning-machines/": {
      "filePath": "products/laser-cleaning-machines/index.tsx",
      "parent": "/products/laser-cleaning-machines"
    },
    "/products/laser-cutting-machines/": {
      "filePath": "products/laser-cutting-machines/index.tsx",
      "parent": "/products/laser-cutting-machines"
    },
    "/products/laser-marking-machines/": {
      "filePath": "products/laser-marking-machines/index.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/dot-marking-machines/hdo-marking-machine/hdo": {
      "filePath": "products/dot-marking-machines/hdo-marking-machine/hdo.tsx",
      "parent": "/products/dot-marking-machines"
    },
    "/products/laser-cleaning-machines/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine": {
      "filePath": "products/laser-cleaning-machines/hcl-laser-cleaning-machine/hcl-laser-cleaning-machine.tsx",
      "parent": "/products/laser-cleaning-machines"
    },
    "/products/laser-cutting-machines/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine": {
      "filePath": "products/laser-cutting-machines/laser-metal-cutting-machine/hcn-c80-cnc-laser-cutting-machine.tsx",
      "parent": "/products/laser-cutting-machines"
    },
    "/products/laser-marking-machines/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source": {
      "filePath": "products/laser-marking-machines/co2-laser-marker/hco-fc-co2-flying-laser-marking-machine-coherent-laser-source.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source": {
      "filePath": "products/laser-marking-machines/co2-laser-marker/hco-sc-co2-laser-marking-machine-coherent-laser-source.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source": {
      "filePath": "products/laser-marking-machines/fiber-laser-marker/hfi-f-fiber-flying-laser-marking-machine-jpt-laser-source.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/fiber-laser-marker/hfi-m-fiber-laser-marker": {
      "filePath": "products/laser-marking-machines/fiber-laser-marker/hfi-m-fiber-laser-marker.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine": {
      "filePath": "products/laser-marking-machines/fiber-laser-marker/hfi-mn-portable-mini-fiber-laser-marking-machine.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source": {
      "filePath": "products/laser-marking-machines/fiber-laser-marker/hfi-s-pulse-fiber-laser-marking-machine-jpt-laser-source.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine": {
      "filePath": "products/laser-marking-machines/portable-laser-marker/hfi-h-model-hanheld-laser-marking-machine.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source": {
      "filePath": "products/laser-marking-machines/uv-laser-marker/huv-fw-uv-flying-laser-marking-machine-jpt-laser-source.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/uv-laser-marker/huv-integrated-fiber-laser-marking-machine": {
      "filePath": "products/laser-marking-machines/uv-laser-marker/huv-integrated-fiber-laser-marking-machine.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine": {
      "filePath": "products/laser-marking-machines/uv-laser-marker/huv-mw-portable-uv-laser-marking-machine.tsx",
      "parent": "/products/laser-marking-machines"
    },
    "/products/laser-marking-machines/uv-laser-marker/huv-sw-machine-crs-laser-source": {
      "filePath": "products/laser-marking-machines/uv-laser-marker/huv-sw-machine-crs-laser-source.tsx",
      "parent": "/products/laser-marking-machines"
    }
  }
}
ROUTE_MANIFEST_END */
