/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products/route'
import { Route as RootLayoutRouteImport } from './routes/_root-layout/route'
import { Route as RootLayoutIndexImport } from './routes/_root-layout/index'
import { Route as RootLayoutContactImport } from './routes/_root-layout/contact'
import { Route as RootLayoutAboutImport } from './routes/_root-layout/about'
import { Route as ProductsProductLayoutRouteImport } from './routes/products/_product-layout/route'
import { Route as ProductsProductLayoutIndexImport } from './routes/products/_product-layout/index'
import { Route as ProductsProductLayoutProductIdImport } from './routes/products/_product-layout/$productId'

// Create/Update Routes

const ProductsRouteRoute = ProductsRouteImport.update({
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const RootLayoutRouteRoute = RootLayoutRouteImport.update({
  id: '/_root-layout',
  getParentRoute: () => rootRoute,
} as any)

const RootLayoutIndexRoute = RootLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

const RootLayoutContactRoute = RootLayoutContactImport.update({
  path: '/contact',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

const RootLayoutAboutRoute = RootLayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

const ProductsProductLayoutRouteRoute = ProductsProductLayoutRouteImport.update(
  {
    id: '/_product-layout',
    getParentRoute: () => ProductsRouteRoute,
  } as any,
)

const ProductsProductLayoutIndexRoute = ProductsProductLayoutIndexImport.update(
  {
    path: '/',
    getParentRoute: () => ProductsProductLayoutRouteRoute,
  } as any,
)

const ProductsProductLayoutProductIdRoute =
  ProductsProductLayoutProductIdImport.update({
    path: '/$productId',
    getParentRoute: () => ProductsProductLayoutRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root-layout': {
      id: '/_root-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRoute
    }
    '/products/_product-layout': {
      id: '/products/_product-layout'
      path: ''
      fullPath: '/products'
      preLoaderRoute: typeof ProductsProductLayoutRouteImport
      parentRoute: typeof ProductsRouteImport
    }
    '/_root-layout/about': {
      id: '/_root-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof RootLayoutAboutImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/_root-layout/contact': {
      id: '/_root-layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof RootLayoutContactImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/_root-layout/': {
      id: '/_root-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutIndexImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/products/_product-layout/$productId': {
      id: '/products/_product-layout/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductLayoutProductIdImport
      parentRoute: typeof ProductsProductLayoutRouteImport
    }
    '/products/_product-layout/': {
      id: '/products/_product-layout/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsProductLayoutIndexImport
      parentRoute: typeof ProductsProductLayoutRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  RootLayoutRouteRoute: RootLayoutRouteRoute.addChildren({
    RootLayoutAboutRoute,
    RootLayoutContactRoute,
    RootLayoutIndexRoute,
  }),
  ProductsRouteRoute: ProductsRouteRoute.addChildren({
    ProductsProductLayoutRouteRoute:
      ProductsProductLayoutRouteRoute.addChildren({
        ProductsProductLayoutProductIdRoute,
        ProductsProductLayoutIndexRoute,
      }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_root-layout",
        "/products"
      ]
    },
    "/_root-layout": {
      "filePath": "_root-layout/route.tsx",
      "children": [
        "/_root-layout/about",
        "/_root-layout/contact",
        "/_root-layout/"
      ]
    },
    "/products": {
      "filePath": "products/route.tsx",
      "children": [
        "/products/_product-layout"
      ]
    },
    "/products/_product-layout": {
      "filePath": "products/_product-layout/route.tsx",
      "parent": "/products",
      "children": [
        "/products/_product-layout/$productId",
        "/products/_product-layout/"
      ]
    },
    "/_root-layout/about": {
      "filePath": "_root-layout/about.tsx",
      "parent": "/_root-layout"
    },
    "/_root-layout/contact": {
      "filePath": "_root-layout/contact.tsx",
      "parent": "/_root-layout"
    },
    "/_root-layout/": {
      "filePath": "_root-layout/index.tsx",
      "parent": "/_root-layout"
    },
    "/products/_product-layout/$productId": {
      "filePath": "products/_product-layout/$productId.tsx",
      "parent": "/products/_product-layout"
    },
    "/products/_product-layout/": {
      "filePath": "products/_product-layout/index.tsx",
      "parent": "/products/_product-layout"
    }
  }
}
ROUTE_MANIFEST_END */
